version: '3.0'

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

services:
  pihole:
    container_name: pihole_unbound
    image: cbcrowe/pihole-unbound:latest
    hostname: pihole # put hostname here <----
    domainname: pihole.domain.com # put domain name here <----
    ports:
      - ?:443/tcp # replace ? with an unused port <----
      - ?:53/tcp # replace ? with an unused port <----
      - ?:53/udp # replace ? with an unused port <----
      - ?:80/tcp # replace ? with an unused port <----
      # - ?:5335/tcp # Uncomment to enable unbound access on local server
      # - ?:22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.xxx.xxx # put device/container ip here <----
      - TZ='America\New_York' # change timezone here if needed <----
      - WEBPASSWORD=password # change password here <----
      - WEBTHEME=${WEBTHEME:-default-dark}
      - REV_SERVER=${REV_SERVER:-false}
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC=true
      - DNSMASQ_LISTENING=single
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped