version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole_trainer # set container name here
    image: pihole/pihole:latest # this pulls from docker (replace latest with arm64 if on raspberry pi)
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "?:53/tcp" # change ? to an unused port <----
      - "?:53/udp" # change ? to an unused port <----
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "?:80/tcp" # change ? to an unused port <---
    environment:
      TZ: 'America/New_York' # Change to your timezone <---
      WEBPASSWORD: password # set a secure password here or it will be random <---
    volumes: # Volumes store your data between container upgrades
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
      #- NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped # can be changed as needed